### ISSUE TITLE
게임 오버 버그

### ISSUE THREAD

**Issue by HJ0oo** [Bheinarl/SSAFY_1st_sem_PJT#23]
## 목적
> 
## 작업 상세 내용
- [x] 게임 오버 이후에도 계속해서 Buy / Sell 가능
- [x] 그 후 next day 누르면 최종값 업데이트 됨
- [x] 최종 점수를 계속해서 조작 가능한 상태

**Comment by Bheinarl** [comment]
게임 종료 시 버튼 삭제로 조작 불가능하게 변경
