### ISSUE TITLE
데이터 수신 방법 변경(nav바에서 데이터 한번에 받고, game에서는 출력만)

### ISSUE THREAD

**Issue by HJ0oo** [Bheinarl/SSAFY_1st_sem_PJT#24]
- [x] 병렬 정렬로 장고에서는 데이터 수신완료, vue 와의 연결 확인해야함
- [x] hj 와 dy 브랜치 master에 merge해야함
- [x] home에서 1번만 데이터 수신하는지 확인
- [x] nav바에서 gamereal을 눌렀을때(gamereal.vue를 호출할때마다 - game 새로 시작할때마다) 난수 생성, 해당 난수부터 10개 데이터
- [x] 데이터를 수신하는 방법에서 > 이미 있는 데이터에서 10개 데이터 필터링하는 방식으로 전환

**Comment by Bheinarl** [comment]
수정 완료
