### ISSUE TITLE
회원가입 로그인 관련

### ISSUE THREAD

**Issue by HJ0oo** [Bheinarl/SSAFY_1st_sem_PJT#47]
## 목적
> 
## 작업 상세 내용
- [x] 회원가입 후 로그인 창으로 넘어가야함
- [x] 로그인 시 토큰이 생성되어 자동 로그인되면 토큰이 생성되지 않는 상황

**Comment by Bheinarl** [comment]
- 회원가입 시 자동로그인이 진행되지 않도록 설정
