### ISSUE TITLE
기능 정리 중

### ISSUE THREAD

**Issue by Bheinarl** [Bheinarl/SSAFY_1st_sem_PJT#78]
- 홈
- 회원가입
- 로그인 / 로그아웃
- 프로필 / 프로필 수정
  - 닉네임, 나이 (수정 가능) // (수정 불가) 자신의 투자 유형, 자신의 모의 투자 게임 최고 기록
- 모의투자게임
  - 공공데이터포털 API 데이터 이용
    - 
  - 차트
  - 뉴스
    - 해당 기간의 네이버 증권 실시간 속보 크롤링
  - 환율 계산기
    - 한국 수출입 은행 openAPI 데이터 이용
    - 환율 알람 기능
    - 알람 설정 시 환율 데이터 조회할 때 환율가가 설정값 아래라면 알람 기능
  - 모의 투자 게임을 통하여 사용자의 투자 경향을 파악
  - 위험 선호도를 다음과 같이 계산
    - 거래 빈도: 30%
    - 보유 기간: 30%
    - 자산 분배율: 20%
    - 섹터 다양성: 10%
    - 종목 분산도: 10%
    - 안정 추구형, 균형 투자형, 공격 투자형, 투기형으로 구분
- 랭킹
  - 최고 점수를 가진 10명의 유저 닉네임(없으면 유저네임)과 점수 공개
- 금융 상품 추천 (펀드, 정기예금, 적금)
  - 펀드 -> 공공데이터포털 API
    - 이름 클릭시 상세 정보 사이트 이동
    - 모의 투자 게임을 통하여 정한 투자 유형별 펀드 종류 추천
  - 정기예금 / 적금 -> 금융감독원 금융상품통합비교공시
    - 은행 클릭 시 자신 주변의 해당 은행 검색
  - 지도
    - 지도 키면 처음은 자신의 위치로 이동
    - 검색 시 자신의 주변으로 해당 검색 결과 출력
- 게시판
  - 생성 / 수정 / 삭제 / 좋아요
  - 자신의 공략과 최고 점수를 자랑

지피티 링크 주세요 논문과 관련된 까먹지말고

투자 유형별 펀드 유형 색 변경 >> 해야됨

**Comment by HJ0oo** [comment]
지피티 링크... 필요한거에요?? 아까 그 링크 안넘겨져서 복붙한건데..!!

**Comment by Bheinarl** [comment]
아니야 괜차낭
